local M = {"Create project",
	"Enter project name:",
	"My project",
	"What does this marker mean?",
	"This marker indicates that the project structure doesn't match the standard. This is not critical - you can still enter Build Project, edit it, and run it. However, there's a chance your project has been damaged and automatic software recovery will be impossible.",
	"levels",
	"scripts",
	"options",
	'resources',
	"run",
	'It\'s empty anyway.\nWith love from your Ponos2d developer',
	"Section under development",
	"delete",
	"duplicate",
	"rename",
	"Create level",
	"Enter name:",
	"import file",
	"text file",
	"folder",
	"Folder name",
	"Enter new name",
	"Do you really want to delete the resource?",
	"You cannot undo this.",
	"cancel",
	"yes, delete",
	"project options",
	"main options",
	"project name",
	"delete project",
	"display configuration",
	"launch and build",
	"Do you really want to delete the script?",
	"Create script",
	"script editor",
	"delete block",
	"copy block",
	"formula editor",
	"Enter text...",
	"copied!",
	"Properties and objects",
	"Logic and operators",
	"Functions and text",
	"Device and application",
	"Project",
	"Data",
	"functions",
	"properties",
	"system",
	"logics",
	"project",
	"data",
	"runtime error",
	"touch began", -- comments for different block groups and hints
	"Use in object touch listener to check if object touch has begun.",
	"moved on object",
	"Use in object touch listener to check if finger is moving on object.",
	"touch ended",
	"Use in object touch listener to check final touch phase.",
	"standard objects",
	"parenting",
	"You can create a parent that will contain other objects. You can move the parent and all objects added to it will move together.",
	"if and else",
	"loops with delay",
	"instant loops",
	"basic properties",
	"stroke (doesn't work on text)",
	"anchor",
	"Object property defining its center. Property is absent for groups. \n\n0, 0 - top left corner of object, \n1, 1 - bottom right corner of object",
	"scale",
	"Changing object width and height rebuilds it and that's good, but if you need to stretch an object use scale\n\n0 - fully compressed, \n1 - original size, \n1+ - stretching beyond original",
	"variable locality",
	"You can create global and local variables. What's the difference? Local variables are not accessible outside the loop where they were created, while global variables are accessible everywhere.",
	"interacting with variables",
	"keys in variables",
	"variables in Ponos2d can store not only values but also tables. \n\nTable consists of keys - variables inside variables.",
	"block selection section",
	"events", -- block categories
	"control",
	"objects",
	"movement",
	"images",
	"data",
	"device",
	"AND",
	"OR",
	"NOT",
	"TRUE",
	"FALSE",
	"place",
	"X:",
	"Y:",
	"object:",
	"set size",
	"%",
	"object:",
	"create rectangle: ",
	"with corners",
	"at position",
	"width:",
	"height:",
	"listen for object touches",
	"local variable",
	"end listener",
	"set object X",
	"to",
	"set object Y",
	"set object",
	"width and height to",
	"set object width",
	"set object height",
	"rotate object",
	"to direction",
	"",
	"if",
	"then",
	"else",
	"then",
	"end condition",
	"repeat",
	"times",
	"end repeat",
	"repeat while",
	"false",
	"with delay",
	"sec.",
	"execute lua-code",
	"create public variable",
	"with value",
	"create local variable",
	"set variable",
	"to value",
	"change variable",
	"by",
	"set in variable",
	"key",
	"to value",
	"create circle",
	"create text",
	"value:",
	"at position",
	"font:",
	"font size:",
	"create image",
	"resource path:",
	"create group",
	"add object",
	"to group",
	"set object transparency",
	"value:",
	"set object visibility",
	"state:",
	"set object fill color",
	"set object stroke color",
	"set stroke thickness",
	"object:",
	"thickness:",
	"set object center",
	"anchor X:",
	"anchor Y:",
	"set object scale",
	"value X:",
	"value Y:",
	"set object X scale",
	"set object Y scale",
	"set object text",
	"set font size",
	'press "+" to add block',
	"object properties",
	"X coordinate",
	"Y coordinate",
	"width",
	"height",
	"X scale",
	"Y scale",
	"rotation",
	"transparency",
	"object visible",
	"anchor X",
	"anchor Y",
	"text",
	"logical expressions",
	"comparison operators",
	"mathematics",
	"sine",
	"cosine",
	"tangent",
	"cotangent",
	"arcsine",
	"arccosine",
	"arctangent",
	"floor",
	"ceil",
	"round",
	"absolute value",
	"square root",
	"power",
	"minimum",
	"maximum",
	"random",
	"decimal logarithm",
	"to degrees",
	"to radians",
	"string length",
	"uppercase",
	"lowercase",
	"substring",
	"repeat string",
	"reverse string",
	"find in string",
    "system information",
	"current FPS",
	"screen width",
	"screen height",
	"variables",
	"decode JSON to {=}",
	"encode {=} to JSON",
	"set key in JSON",
	"get key from JSON",
	"text properties",
	"hello from console!",
	"Text",
	"Enter text...",
	"done",
	"levels",
	"Ponos2d Settings",
	"set object anchor X",
	"set object anchor Y",
	"user language",
	"enable English blocks",
	"enable English formulas",
	"error notification on launch",
	"nothing",
	'press "+" to create script',
	"(copy)",
	"mathematics",
	"text operations",
	"remove listener from object",
	"type",
	"ask",
	"and save answer to",
	"Welcome to Ponos2d!",
	"Please select interface language:",
	"Skip?",
	"By skipping the start screen, you lose nothing.",
	"yes, skip",
	"no, stay",
	"Intuitive programming",
	"Blocks are simple and even a child can create a game from them. For example, clicker game script:",
	"Functionality",
	"Projects in Ponos2d compile into real code. Blocks make the process easy and comfortable, while Lua and Solar2D ensure optimization of your projects.",
	"Below you can see screenshots of games created with Corona Labs engine",
	"We add new blocks for you so you can bring your ideas to life without programming skills!",
	"Go to menu",
	"Ready to start using Ponos2d?",
	"Coming soon!",
	"It's empty here!",
    "wait",
    "sec.",
    "wait while",
    "repeat while",
    "becomes false",
    "create function",
    "create local function",
    "with parameters",
    "with parameters in",
    "new function...",
    "in variable", -- context: create function _ in variable _ with parameters in _
	"set sprite to object",
    "from resource",
    "touch", --context: remove listener from object _ type: ["touch"]
	"radius",
	"set focus on",
	"remove touch focus",
	"Register",
	"Settings",
	"Under development!",
	"Follow updates so you don't miss out",
	"interface sounds",
	"use system font",
	"save scroll position in scripts",
	"open script at saved position",
	{{"Characters", {{"Top-down Player", "Player.png"}, {"Big man", "Big man.png"}, {"Man in box", "box player.png"}, {"Little Red Riding Hood", "red player.png"}, {"Armed player", "guitar man.png"},}},{ "Items", {{"Bottle", "bottle water.png"},{"Campfire", "fire place.png"},{"Green ball", "green ball.png"},{"Watermelon", "melon.png"},{"Rocks", "rocks.png"},{"Stick", "stic.png"},{"Tree", "tree.png"},{"Big sword", "big sword.png"},{"Blueberry", "blue berry.png"},{"Bomb", "bomb.png"},{"Top-down car", "car.png"},{"Gold coin", "gold coin.png"},{"Iron coin", "iron coin.png"},{"Stone coin", "stone coin.png"},{"Side grass ground", "grass ground.png"},{"Iron axe", "Iron axe.png"},{"Key", "key.png"},}},},
	"Local library",
	"new file..",
	"import file",
	"choose from library",
	"copied!",
	"Copy", -- copy file
	"project orientation",
	"vertical",
	"horizontal",
	"export project lua-code",
	"run project in CoronaLabs Solar2D",
	"build Solar2D project",
	"CoronaLabs Solar2D project build with everything necessary",
	"compiled code",
	"copied to clipboard",
	"Do you really want to delete the project?",
	"No, keep",
	"Yes, delete",
	"project %s deleted",
	"syntax error: ",
	"clear", -- console
	"close", -- console
	"console cleared!",
	"width", -- Next are blocks and formulas again
	"height",
	"transparency",
	"X scale",
	"Y scale",
	"rotation",
	"dynamic",
	"static",
	"kinematic",
	"on",
	"on",
	"yes",
	"no",
	"touch",
	"collision",
	"pre-collision",
	"post-collision",
	"set object variable",
	"key:",
	'value:',
	"listen for event",
	"of object",
	"to function",
	"in",
	"change X",
	"change Y",
	"animate",
	"property",
	"to value:",
	"in",
	"sec.",
	"easing:",
	"set camera position to",
	"set camera X to",
	"set camera Y to",
	"add physics",
	"type",
	"density",
	"restitution",
	"friction",
	"gravity",
	"remove physics",
	"change physics type",
	"to",
	"update hitbox",
	"rectangular hitbox",
	"circular hitbox",
	"radius",
	"polygon hitbox",
	"points {x1,y1,x2,y2...}",
	"velocity",
	"X velocity",
	"Y velocity",
	"apply force",
	"force X:",
	"force Y:",
	"offset X:",
	"offset Y:",
	"apply impulse",
	"impulse X:",
	"impulse Y:",
	"offset X:",
	"offset Y:",
	"angular velocity",
	"torque",
	"angular impulse",
	"object gravity",
	"scale",
	"ghost mode (collisions)",
	"state",
	"fixed rotation",
	"bullet mode",
	"linear damping",
	"angular damping",
	"wake object",
	"hinge",
	"base",
	"object",
	"point X:",
	"point Y:",
	"distance",
	"body A",
	"body B",
	"A: X",
	"Y",
	"B: X",
	"weld",
	"piston", -- as joint name
	"piston", -- as piston object name
	"axis X:",
	"axis Y:",
	"wheel", -- as joint name
	"wheel", -- as wheel object name
	"touch", -- as joint name
	"rope",
	"delete joint",
	"hinge motor",
	"speed",
	"max torque",
	"hinge limits",
	"min",
	"max",
	"distance settings",
	"damping %",
	"frequency",
	"length",
	"touch target",
	"contact restitution",
	"contact friction",
	"tangential speed",
	"disable collision",
	"start physics",
	"pause physics",
	"resume physics",
	"stop physics",
	"show hitboxes",
	"hide hitboxes", -- physics ended
	"rotate right",
	'execute from',
	'to',
	'in variable',
	'end execution',
	"execute when",
	"false",
	"wait",
	"return",
	"print to console",
	"show message window",
	"create container",
	"width:",
	"height:",
	"delete object",
	"object tap animation",
	"effect strength",
	"set object HEX color",
	"set stroke HEX color",
	"end wait",
	"local function",
	"parameters in",
	"global function",
	"parameters in",
	"end function",
	"call function",
	"parameters:",
	"true",
	"behavior",
	"physics",
	"This is a message!",
	"What is your name?",
	"animations",
	"color and texture",
	"control",
	"world physics",
	"contacts and collisions",
	"joint settings",
	"joints (connections)",
	"physics properties",
	"forces and velocity",
	"hitbox",
	"physics body",
	"Scene positioning",
	"Position and rotation",
	"object interactions",
	"functions",
	"Comment",
	"gravity for all",
	"Script_",
	"got it",
	'Project "%s" launched',
	"launch interrupted by error: ",
	"Enter table key...", 
	'view v("variable")[key]',
	'or change current',
	"color picker",
	"HEX color picker",
	"helper functions",
	"camera position X",
	"camera position Y",
	"RGB to HEX",
	"center screen X",
	"center screen Y",
	"World and touch",
	'select file type...',
	'image',
	'audio',
	'document',
	'AAAAAAAAAAAA','AAAAAAAAAAAA','AAAAAAAAAAAA','AAAAAAAAAAAA','AAAAAAAAAAAA','AAAAAAAAAAAA','AAAAAAAAAAAA','AAAAAAAAAAAA','AAAAAAAAAAAA','AAAAAAAAAAAA','AAAAAAAAAAAA',
}

return M